# This file is part of pyunicorn.
# Copyright (C) 2008--2026 Jonathan F. Donges and pyunicorn authors
# URL: <https://www.pik-potsdam.de/members/donges/software-2/software>
# License: BSD (3-clause)


# documentation & validation ==================================================

# - https://docs.travis-ci.com/user/reference/overview
# - https://docs.travis-ci.com/user/build-matrix/
# - https://docs.travis-ci.com/user/multi-os/

# - https://docs.travis-ci.com/user/build-config-validation/
# - https://config.travis-ci.com/explore


# meta ========================================================================

# enable build config validation
version: ~> 1.0

# save Travis budget
if: branch = main

# report outcomes
notifications:
  email:
    on_success: change
    on_failure: always


# default jobs: Linux, all Python versions ====================================

os: linux
dist: focal
arch: arm64
virt: lxd
language: generic

env:
  global:
    - | # limit procs to available cores
      TOX_JOBS=2
    - FORCE_COLOR=1
    - RUST_LOG=debug
  jobs:
    - PYTHON=3.14
    - PYTHON=3.13
    - PYTHON=3.12
    - PYTHON=3.11
    - PYTHON=3.10

before_install:
  - | # install executables and `uv`
    sudo apt-get -y install pandoc
    export UV_UNMANAGED_INSTALL="${HOME}/.local/bin"
    travis_retry wget -qO- https://astral.sh/uv/install.sh | sh
    export PATH="${UV_UNMANAGED_INSTALL}:${PATH}"; hash -r

install:
  - | # create `uv` environment and instantiate `pyproject.toml`
    uv venv --python ${PYTHON}
    uv sync --all-groups --no-group dev

script:
  - | # run test suite
    uv run --no-sync tox -v

# report statistics
after_success: codecov


# modified job: Windows, newest Python version ================================
# (inherit only 1st `env.jobs` entry)

jobs:
  fast_finish: true
  include:
    - os: windows
      language: shell
      before_install:
        - | # install executables and `uv`
          travis_retry choco install pandoc uv
