# This file is part of pyunicorn.
# Copyright (C) 2008--2026 Jonathan F. Donges and pyunicorn authors
# URL: <https://www.pik-potsdam.de/members/donges/software-2/software>
# License: BSD (3-clause)

# package ======================================================================

[build-system]
requires = [
  "setuptools>=75",
  "wheel",
  "Cython>=3.1",
  "numpy>=2.2"
]
build-backend = "setuptools.build_meta"

[project]
name = "pyunicorn"
version = "1.0.0"
description = "Unified complex network and recurrence analysis toolbox"
keywords = [
  "complex network", "nonlinear time series analysis",
  "climate network", "recurrence plot", "surrogate model"
]
readme = "README.rst"
authors = [
  { name = "Jonathan F. Donges", email = "donges@pik-potsdam.de" }
]
maintainers = [
  { name = "Fritz Kühlein", email = "fritzku@pik-potsdam.de" },
  { name = "Boyan Beronov", email = "beronov@cs.ubc.ca" },
]
license = "BSD-3-Clause"
license-files = ["LICENSE.txt"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: GIS",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Scientific/Engineering :: Physics",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Framework :: Pytest",
]
requires-python = ">=3.10"
dependencies = [
  "numpy>=2.2",
  "scipy>=1.15",
  "igraph>=1.0",
  "h5netcdf[h5py]>=1.8",
  "tqdm>=4.67",
]

[dependency-groups]
dev = [
  "Cython>=3.1",
  "ipykernel>=7.3.0",
]
test = [
  "tox>=4.11",
  "ruff>=0.15",
  "pytest>=8.4",
  "pytest-xdist>=3.7",
  "pytest-cov>=7.0",
  "joblib>=1.5",
  "networkx>=3.4",
  "matplotlib>=3.10",
  "cartopy>=0.25",
  "requests>=2.33",
  "psutil>=7.1",
]
docs = [
  "sphinx>=8.1",
  "nbsphinx>=0.9.7",
  "ipython>=8.39",
  "pandoc>=2.4",
  "matplotlib>=3.10",
]
ci = [
  "codecov>=2.1.13",
]

[tool.uv]
default-groups = ["dev", "test", "docs"]

[project.urls]
Homepage = "https://www.pik-potsdam.de/members/donges/software-2/software"
Documentation = "http://www.pik-potsdam.de/~donges/pyunicorn/"
Repository = "https://github.com/pik-copan/pyunicorn"
Changelog = "https://github.com/pik-copan/pyunicorn/blob/main/CHANGELOG.rst"
Issues = "https://github.com/pik-copan/pyunicorn/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = [ "src" ]
include = [ "pyunicorn*" ]

# testing ======================================================================

[tool.tox]
env_list = ["lint", "test", "docs"]
skipsdist = true

[tool.tox.env_run_base]
sitepackages = true
set_env = { PYTHONPATH = "{tox_root}/src" }
pass_env = ["WINDIR", "LC_ALL"]
allowlist_externals = ["ruff", "pytest", "sphinx-build", "pandoc"]

[tool.tox.env.lint]
package = "skip"
commands = [[
  "ruff", "check"
]]

[tool.tox.env.test]
package = "sdist"
commands = [["pytest", "-n", "{env:TOX_JOBS:auto}", "--cov"]]

[tool.tox.env.docs]
package = "sdist"
commands = [[
  "sphinx-build", "-v", "-j", "{env:TOX_JOBS:8}", "-W", "-b", "html",
  "-d", "{envtmpdir}/doctrees", "docs/source", "{envtmpdir}/html"
]]

[tool.pytest.ini_options]
minversion = 8.4
addopts = "-v -r a -n auto"
testpaths = ["tests"]
python_files = ["test*.py", "Test*.py"]
norecursedirs = [".git", ".cache", ".tox", ".ropeproject", "build"]
filterwarnings = [
  "ignore:datetime.datetime.utcfromtimestamp():DeprecationWarning:dateutil|tqdm",
]

[tool.coverage.run]
parallel = true
concurrency = ["multiprocessing"]
source = ["src/pyunicorn"]

# static analysis ==============================================================

[tool.ruff]
line-length = 100

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "W"]
ignore = [
  "E702",  # "multiple-statements-on-one-line-colon"
  ]

[tool.ruff.lint.per-file-ignores]
# Ignore `F401` (unused-import) in all `__init__.py` files
"__init__.py" = ["F401"]
